# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-13 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('jornada', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
